### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghutchis** [globus-labs/conformer-optimization#1]
This looks like a nice example of BoTorch / GPyTorch for conformer optimization.

What license is the code? Would you be interested in collaborating, or is this a finished project for now?

**Comment by WardLT** [comment]
Thanks, @ghutchis ! 

I'm going to put in an MIT license into the repo. This was a quick hack for a collaborator in need of a conformer optimizer that worked with a DFT code, and I'm happy to extend it together (you should also have gotten an email reply from me)

**Comment by WardLT** [comment]
Fixed
